// Merge user-provided travel detail tables into data/indonesia.js, data/cambodia.js, data/vietnam.js
// Run: node scripts/merge_travel_data.mjs
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA = resolve(__dirname, '..', 'data');

const { indonesiaData } = await import('../data/indonesia.js');
const { cambodiaData } = await import('../data/cambodia.js');
const { vietnamData } = await import('../data/vietnam.js');

// Row shape: R(payment, culture, dress, gettingAround, food, stay, transport, cost, hours, emergency, hospitals, water, shops)
const R = (payment, culture, dress, arnd, food, stay, transport, cost, hours, emerg, hosp, water, shops) => ({
  paymentMethods: payment,
  cultureEtiquette: culture,
  dressCode: dress,
  gettingAround: arnd,
  food,
  stay,
  transport,
  costPerDay: cost,
  openingHours: hours,
  emergencyNumbers: emerg,
  hospitals: hosp,
  waterSource: water,
  shops,
});

// ---------------------------------------------------------------------------
// INDONESIA
// ---------------------------------------------------------------------------
const IND = {
  'indonesia-bali': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Balinese Hindu culture is expressed through temples, ceremonies, daily offerings and traditional arts. Wear modest clothing at temples, use a sarong and sash when required, avoid stepping on offerings and do not interrupt ceremonies. Do not enter restricted sacred areas, climb temple structures or behave disrespectfully at religious sites; follow Bali\'s visitor regulations.',
    'Light casual clothing; sarong for temples',
    'Scooter, Taxi, Ride-hailing',
    'Babi Guling, Ayam Betutu',
    'Hotel, Villa, Resort, Homestay',
    'Plane, Car',
    'Rp1,500,000',
    'Open 24 Hours',
    'Medical Emergency / Ambulance 119 Police 110 Fire & Rescue 113 Search & Rescue (BASARNAS) 115 Disaster Emergency (BNPB) 117 Tourist Police 110',
    'Sanglah General Hospital (Denpasar)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Indomaret, Alfamart, Pepito Market'
  ),
  'indonesia-komodo': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The park is connected to the culture of communities living around Komodo, Rinca and Flores and is the natural habitat of Komodo dragons. Stay with a ranger, remain calm, keep a safe distance from wildlife and respect nearby villages. Do not feed, touch, chase or disturb Komodo dragons; stay on authorised routes and obey ranger instructions.',
    'Light outdoor clothing, hiking shoes',
    'Walking, Boat',
    'Se\'i Sapi, Ikan Kuah Asam',
    'Hotel, Resort, Liveaboard',
    'Plane, Boat',
    'Rp2,500,000',
    '06:00–17:00',
    '',
    'Siloam Hospital Labuan Bajo',
    'Fresh Water Supply, Bottled Water',
    'Komodo Mart, Labuan Bajo Supermarket'
  ),
  'indonesia-rajaampat': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Indigenous Papuan and island communities have strong customary relationships with the sea and natural environment. Ask permission before photographing residents, dress respectfully in villages and support local guides and businesses. Follow marine-protected-area zoning; do not damage coral, collect marine life or fish without the required customary permission.',
    'Light breathable clothing, reef-safe swimwear',
    'Boat, Speedboat',
    'Papeda, Ikan Bakar',
    'Resort, Homestay, Liveaboard',
    'Plane, Ferry/Speedboat',
    'Rp3,000,000',
    'Open 24 Hours',
    '',
    'Raja Ampat Regional Hospital (Waisai)',
    'Rainwater Collection, Bottled Water',
    'Waisai Market, Raja Ampat Mart'
  ),
  'indonesia-wakatobi': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Wakatobi is home to maritime communities, including Bajo sea-oriented traditions, alongside strong coral-conservation values. Respect fishing communities, avoid touching coral and follow instructions from dive operators and local guides. Do not collect coral, shells or protected marine animals; follow national-park diving, boating and conservation rules.',
    'Light clothing, reef-safe swimwear',
    'Boat, Speedboat',
    'Parende, Kasoami',
    'Resort, Homestay',
    'Plane, Ferry',
    'Rp2,200,000',
    '07:00–17:00',
    '',
    'Wakatobi Regional Hospital',
    'Municipal Water, Bottled Water',
    'Wangi-Wangi Market, Indomaret'
  ),
  'indonesia-morotai': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Morotai combines North Maluku island culture with significant Second World War heritage. Ask before entering villages or photographing residents and do not remove objects from historical sites. Do not take war relics, damage archaeological remains or disturb protected marine life; follow dive-safety zones.',
    'Light tropical clothing',
    'Car, Motorcycle',
    'Gohu Ikan, Popeda',
    'Hotel, Resort',
    'Plane, Car',
    'Rp1,500,000',
    'Open 24 Hours',
    '',
    'Morotai Regional Hospital',
    'Municipal Water, Bottled Water',
    'Morotai Market, Alfamart'
  ),
  'indonesia-gilitrawangan': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The island has Sasak cultural influences and a tourism community centred on marine recreation. Dress respectfully away from beaches, keep noise low near residential and religious areas and protect the reef. Do not damage coral, litter or use illegal drugs; follow local boating, diving and marine-conservation rules.',
    'Beachwear, light clothing',
    'Walking, Bicycle, Horse Cart',
    'Ayam Taliwang, Plecing Kangkung',
    'Hotel, Resort, Hostel',
    'Plane, Ferry',
    'Rp1,200,000',
    'Open 24 Hours',
    '',
    'Gili Medical Center',
    'Municipal Water, Bottled Water',
    'Alfamart, Local Convenience Stores'
  ),
  'indonesia-kalibiru': R(
    'Cash (IDR), QRIS',
    'The site is part of a Papuan landscape managed with local community and customary values. Use local guides, ask before photographing people, keep noise low and avoid using products that pollute the river. Do not litter, damage vegetation or enter restricted customary areas; follow village access and conservation rules.',
    'Quick-dry clothing, water shoes',
    'Walking',
    'Papeda, Ikan Bakar',
    'Homestay',
    'Boat',
    'Rp800,000',
    '07:00–17:00',
    '',
    'Waisai Health Centre (Puskesmas)',
    'Natural Spring, Bottled Water',
    'Waisai Market'
  ),
  'indonesia-maron': R(
    'Cash (IDR), QRIS',
    'The river is surrounded by rural Javanese communities and agricultural landscapes. Greet residents politely, dress modestly, use authorised boat operators and avoid disrupting fishing activities. Wear required safety equipment, do not litter and follow boat-capacity and local river-safety regulations.',
    'Light clothing, sandals or water shoes',
    'Walking, Canoe',
    'Pecel Pacitan, Sate Tuna',
    'Guesthouse, Homestay',
    'Car',
    'Rp600,000',
    '07:00–17:00',
    '',
    'Pacitan Regional Hospital',
    'River Water, Bottled Water',
    'Pacitan Market, Indomaret'
  ),
  'indonesia-riamkanan': R(
    'Cash (IDR), QRIS',
    'The reservoir area reflects Banjar culture and the livelihoods of fishing and waterside communities. Respect fish farms and homes, ask permission before photographing residents and use local boat services responsibly. Do not enter restricted dam areas, interfere with fishing equipment or travel by boat without required safety equipment.',
    'Light clothing, hat, sandals',
    'Boat',
    'Soto Banjar, Patin Bakar',
    'Guesthouse, Homestay',
    'Car, Boat',
    'Rp700,000',
    '08:00–17:00',
    '',
    'Riam Kanan Health Centre (Puskesmas)',
    'Reservoir Water, Bottled Water',
    'Martapura Market, Alfamart'
  ),
  'indonesia-bromo': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Mount Bromo is sacred to the Tenggerese people, who hold ceremonies such as Yadnya Kasada. Respect ceremonies, temples and offerings; dress warmly and modestly and avoid disturbing horses or local worshippers. Follow national-park routes, closures and permits; do not enter dangerous crater zones, litter or damage protected land.',
    'Warm jacket, long pants, hiking shoes',
    'Jeep, Horse, Walking',
    'Rawon, Bakso Malang',
    'Hotel, Guesthouse',
    'Car, Jeep',
    'Rp900,000',
    '07:00–17:00',
    '',
    'Probolinggo Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Cemoro Lawang Shops'
  ),
  'indonesia-puncakjaya': R(
    'Cash (IDR), Bank Transfer, Credit/Debit Card',
    'The surrounding highlands are home to Indigenous Papuan communities with distinct languages, lands and customary traditions. Use authorised local guides, obtain community permission, avoid photographing people without consent and respect sacred land. Climbing requires permits and organised access; do not enter restricted areas, remove cultural objects or ignore security instructions.',
    'Cold-weather hiking gear, waterproof jacket, hiking boots',
    '4WD, Hiking',
    'Papeda, Ulat Sagu',
    'Camping, Expedition Camp',
    'Plane, 4WD',
    'Rp6,000,000',
    'Permit Required (24 Hours)',
    '',
    'Timika Regional Hospital',
    'Mountain Streams, Bottled Water',
    'Timika Supermarket'
  ),
  'indonesia-semeru': R(
    'Cash (IDR), QRIS',
    'The mountain is culturally significant in Javanese and Hindu traditions and lies within Bromo Tengger Semeru National Park. Respect sacred beliefs, maintain silence where requested and carry all rubbish out of the park. Climb only when officially open and with required registration; obey exclusion zones because volcanic activity may cause closures.',
    'Warm jacket, hiking clothes, hiking boots',
    'Hiking',
    'Rawon, Rujak Cingur',
    'Camping',
    'Car',
    'Rp800,000',
    '24 Hours (Registration Required)',
    '',
    'Lumajang Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Ranupani Village Shops'
  ),
  'indonesia-goajomblang': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The cave lies in a rural Javanese area where local guides manage access and share knowledge of the landscape. Listen to guides, wear provided safety equipment and avoid loud behaviour or touching delicate cave features. Use authorised operators, follow rope-safety procedures and do not damage, write on or remove cave formations.',
    'Comfortable clothes, closed-toe shoes',
    'Walking, Rope Access',
    'Gudeg, Bakpia',
    'Hotel, Homestay',
    'Car',
    'Rp900,000',
    '08:00–14:00',
    '',
    'Wonosari Regional Hospital',
    'Groundwater, Bottled Water',
    'Local Convenience Stores, Indomaret Wonosari'
  ),
  'indonesia-marospangkep': R(
    'Cash (IDR), QRIS',
    'The karst area contains ancient rock art and is associated with Bugis-Makassar culture and nearby rural communities. Do not touch paintings, ask before photographing residents and use local guides in caves and forests. Damaging rock art, removing archaeological material or vandalising caves is prohibited; follow conservation-area access rules.',
    'Light outdoor clothing, hiking shoes',
    'Walking',
    'Coto Makassar, Konro',
    'Hotel, Resort',
    'Car',
    'Rp900,000',
    '08:00–17:00',
    '',
    'Salewangang Regional Hospital (Maros)',
    'Groundwater, Bottled Water',
    'Maros Market, Indomaret'
  ),
  'indonesia-goarangko': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The cave is visited through communities around Labuan Bajo and reflects the region\'s coastal tourism culture. Use local boat operators, wear suitable clothing and avoid loud behaviour, soap or chemicals in the natural pool. Do not damage rock formations, leave rubbish, enter unsafe sections or ignore guide and tide instructions.',
    'Swimwear, quick-dry clothing, water shoes',
    'Boat, Swimming',
    'Se\'i Sapi, Jagung Bose',
    'Hotel, Resort',
    'Car, Boat',
    'Rp1,200,000',
    '08:00–17:00',
    '',
    'Siloam Hospital Labuan Bajo',
    'Natural Spring, Bottled Water',
    'Labuan Bajo Supermarket'
  ),
  'indonesia-tangkubanparahu': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The volcano is associated with the Sundanese legend of Sangkuriang and is important to West Javanese tourism culture. Respect local vendors and beliefs, remain on paths and avoid entering sulphur areas when instructed not to. Obey volcanic hazard closures, barriers and official trails; do not approach restricted craters or throw rubbish.',
    'Warm jacket, long pants, closed-toe shoes',
    'Walking',
    'Batagor, Siomay',
    'Hotel, Resort',
    'Car',
    'Rp900,000',
    '08:00–17:00',
    '',
    'Bandung Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Lembang Market, Indomaret'
  ),
  'indonesia-batur': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Mount Batur is sacred in Balinese Hinduism and is associated with temples, farming communities and religious ceremonies. Dress respectfully near temples, use recognised guides, avoid interrupting ceremonies and do not leave rubbish on the mountain. Obey trekking routes, volcanic warnings and sacred-area restrictions; do not enter closed zones or damage shrines.',
    'Hiking clothes, warm jacket, hiking shoes',
    'Hiking',
    'Babi Guling, Ayam Betutu',
    'Hotel, Resort',
    'Car',
    'Rp900,000',
    'Open 24 Hours',
    '',
    'Bangli Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Kintamani Market, Indomaret'
  ),
  'indonesia-kelimutu': R(
    'Cash (IDR), QRIS',
    'Local Lio communities regard the crater lakes as spiritually significant places connected with ancestral beliefs. Respect local spiritual beliefs, keep noise low, stay behind barriers and use local guides where appropriate. Do not enter the crater lakes, cross safety barriers, litter or remove plants and rocks from the national park.',
    'Warm jacket, hiking shoes',
    'Walking',
    'Jagung Bose, Se\'i Sapi',
    'Hotel, Homestay',
    'Plane, Car',
    'Rp1,200,000',
    '06:00–17:00',
    '',
    'Ende Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Moni Village Shops'
  ),
  'indonesia-kelingking': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The site is part of Nusa Penida\'s Balinese Hindu island culture and coastal community. Dress respectfully away from the beach, avoid blocking narrow trails and respect nearby temples and offerings. Follow cliff and beach safety barriers; do not enter closed routes, litter, damage cliffs or disturb protected wildlife.',
    'Beachwear, comfortable sandals',
    'Walking',
    'Lawar, Seafood Bakar',
    'Villa, Resort',
    'Car',
    'Rp1,000,000',
    'Open 24 Hours',
    '',
    'Nusa Medica Clinic (Nusa Penida)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Nusa Penida Mart, Indomaret'
  ),
  'indonesia-tanahlot': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Tanah Lot is an important Balinese Hindu sea temple associated with worship, ceremonies and coastal spirituality. Wear respectful clothing, avoid interrupting worship, follow temple staff and do not step on offerings. Visitors may not enter worship-only areas without permission; obey tide closures and do not climb restricted temple rocks.',
    'Modest clothing; sarong for temple areas',
    'Walking',
    'Babi Guling, Lawar',
    'Hotel, Villa',
    'Car',
    'Rp900,000',
    '06:00–19:00',
    '',
    'Kasih Ibu Hospital (Tabanan)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Tanah Lot Souvenir Market, Indomaret Tabanan'
  ),
  'indonesia-rajaampatislands': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The islands combine Indigenous Papuan village traditions with customary marine stewardship. Ask permission before village visits and photography, dress modestly and avoid touching reefs or wildlife. Follow marine-park zoning and visitor requirements; collecting coral, damaging reefs and unauthorised tourist fishing are prohibited.',
    'Light clothing, reef-safe swimwear',
    'Boat, Speedboat',
    'Papeda, Fresh Seafood',
    'Resort, Homestay, Liveaboard',
    'Plane, Ferry/Speedboat',
    'Rp3,000,000',
    'Open 24 Hours',
    '',
    'Raja Ampat Regional Hospital (Waisai)',
    'Rainwater Collection, Bottled Water',
    'Waisai Market'
  ),
  'indonesia-gunungleuser': R(
    'Cash (IDR), Bank Transfer, QRIS',
    'The park borders Gayo, Alas, Karo and other Sumatran communities and supports traditional forest-linked livelihoods. Use licensed guides, keep distance from orangutans, do not feed wildlife and respect village customs. Feeding, touching, capturing or disturbing wildlife is prohibited; stay on authorised routes and follow park permits.',
    'Long sleeves, hiking clothes, trekking boots',
    'Hiking',
    'Mie Aceh, Gayo Coffee',
    'Eco Lodge, Jungle Lodge',
    'Plane, Car',
    'Rp1,500,000',
    '07:00–17:00',
    '',
    'Kutacane Regional Hospital',
    'River Water, Bottled Water',
    'Bukit Lawang Shops'
  ),
  'indonesia-tanjungputing': R(
    'Cash (IDR), Credit/Debit Card, Bank Transfer',
    'The park is linked to Dayak and riverside communities and is known for orangutan conservation and klotok boat travel. Keep quiet at feeding stations, follow ranger instructions and do not touch or feed orangutans independently. Do not remove wildlife or plants, leave designated routes, use unauthorised feeding or pollute the Sekonyer River.',
    'Light clothing, long sleeves, trekking shoes',
    'Boat',
    'Soto Banjar, Patin Bakar',
    'Jungle Lodge, Houseboat',
    'Plane, Boat',
    'Rp2,000,000',
    '07:00–17:00',
    '',
    'Pangkalan Bun Hospital',
    'River Water, Bottled Water',
    'Pangkalan Bun Market, Indomaret'
  ),
  'indonesia-ujungkulon': R(
    'Cash (IDR), QRIS',
    'The park lies in Banten and is connected to Sundanese coastal communities and conservation of the Javan rhinoceros. Use authorised guides, keep noise low, respect village land and avoid seeking or approaching rhinos. Access to sensitive rhino habitat is restricted; hunting, collecting wildlife and entering closed zones are prohibited.',
    'Light clothing, trekking shoes',
    'Boat, Hiking',
    'Sate Bandeng, Rabeg',
    'Eco Lodge, Camping',
    'Car, Boat',
    'Rp1,300,000',
    '07:30–16:30',
    '',
    'Pandeglang Regional Hospital',
    'River Water, Bottled Water',
    'Sumur Village Shops'
  ),
  'indonesia-gilimeno': R(
    'Cash (IDR), QRIS',
    'The sanctuary supports local conservation efforts within the Sasak-influenced Gili island community. Do not touch turtles, keep a respectful swimming distance and avoid standing on coral. Do not capture, feed or harass turtles; collecting eggs, coral or protected marine life is prohibited.',
    'Swimwear, reef-safe clothing',
    'Walking, Bicycle',
    'Ayam Taliwang, Plecing Kangkung',
    'Resort, Hotel',
    'Plane, Boat',
    'Rp1,200,000',
    '08:00–17:00',
    '',
    'Gili Medical Center',
    'Municipal Water, Bottled Water',
    'Local Convenience Stores'
  ),
  'indonesia-tangkahanelephant': R(
    'Cash (IDR), QRIS',
    'The destination involves local community-based ecotourism near the Leuser ecosystem and Sumatran elephant conservation. Follow mahout and guide instructions, avoid forcing contact with elephants and respect local villages. Do not feed elephants without permission, use harmful handling practices or enter protected forest without authorised access.',
    'Comfortable outdoor clothing, trekking shoes',
    'Walking',
    'Mie Aceh, Gayo Coffee',
    'Eco Lodge, Guesthouse',
    'Plane, Car',
    'Rp1,500,000',
    '08:00–17:00',
    '',
    'Tangkahan Health Centre (Puskesmas)',
    'River Water, Bottled Water',
    'Tangkahan Village Shops'
  ),
  'indonesia-waykambas': R(
    'Cash (IDR), QRIS',
    'The park works with Lampung communities and protects elephants, rhinos and lowland Sumatran ecosystems. Observe animals quietly, follow rangers and avoid demanding performances or direct wildlife contact. Entering restricted rhino areas, feeding wildlife, hunting or removing forest materials is prohibited.',
    'Long sleeves, trekking clothes, hiking shoes',
    'Safari Vehicle',
    'Seruit, Tempoyak',
    'Eco Lodge, Hotel',
    'Plane, Car',
    'Rp1,300,000',
    '07:00–17:00',
    '',
    'Way Kambas Health Centre (Puskesmas)',
    'River Water, Bottled Water',
    'Labuhan Ratu Market'
  ),
  'indonesia-tangkoko': R(
    'Cash (IDR), QRIS',
    'The reserve is surrounded by Minahasan communities and protects endemic Sulawesi wildlife such as tarsiers and macaques. Keep quiet, avoid flash photography of nocturnal animals and do not feed macaques or tarsiers. Do not capture, feed, touch or disturb protected wildlife; visitors must follow reserve routes and guide instructions.',
    'Long sleeves, trekking shoes',
    'Walking',
    'Tinutuan, Cakalang Fufu',
    'Eco Lodge, Resort',
    'Plane, Car',
    'Rp1,500,000',
    '05:30–18:00',
    '',
    'Bitung Regional Hospital',
    'Natural Spring, Bottled Water',
    'Bitung Market, Indomaret'
  ),
  'indonesia-monkeyforest': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The forest is a Balinese Hindu temple complex based on harmony between people, nature and spirituality. Do not touch, tease or stare aggressively at monkeys; secure food and belongings and respect temple areas. Feeding is restricted to authorised arrangements; do not enter sacred areas improperly or harm, capture or provoke monkeys.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Babi Guling, Bebek Betutu',
    'Hotel, Villa',
    'Car',
    'Rp900,000',
    '09:00–18:00',
    '',
    'Ubud Care Clinic',
    'Tap Water (Not Drinkable), Bottled Water',
    'Coco Supermarket Ubud, Bintang Supermarket'
  ),
  'indonesia-tamansafari': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The park combines Indonesian family recreation with wildlife education, rescue and conservation programmes. Remain inside vehicles where instructed, drive slowly and follow staff directions around animal enclosures. Do not leave vehicles in restricted zones, feed prohibited food, cross barriers or disturb animals.',
    'Comfortable casual clothing',
    'Safari Vehicle',
    'Sate Maranggi, Sundanese Grilled Fish',
    'Hotel, Resort',
    'Car',
    'Rp900,000',
    '09:00–17:00',
    '',
    'Bogor Regional Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Indomaret, Alfamart'
  ),
  'indonesia-borobudur': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Borobudur is a major Buddhist monument and pilgrimage site representing ancient Javanese Buddhist heritage. Dress modestly, speak quietly, respect worshippers and avoid sitting or standing on stupas and carvings. Use the correct ticket for courtyard or temple-structure access; follow timed entry, footwear and monument-protection rules.',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Gudeg, Bakpia',
    'Hotel',
    'Car',
    'Rp700,000',
    '06:30–17:00',
    '',
    'Borobudur Health Centre (Puskesmas)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Borobudur Market, Indomaret'
  ),
  'indonesia-mendut': R(
    'Cash (IDR), QRIS',
    'Mendut is an ancient Buddhist temple that remains connected to Buddhist worship and Vesak traditions. Dress modestly, remain quiet during prayers, remove shoes where instructed and do not touch sacred statues. Do not climb, vandalise or remove stones and artefacts; follow heritage-site boundaries and ticket requirements.',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Gudeg, Bakpia',
    'Hotel',
    'Car',
    'Rp600,000',
    '08:00–17:00',
    '',
    'Borobudur Health Centre (Puskesmas)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Borobudur Market'
  ),
  'indonesia-pawon': R(
    'Cash (IDR), QRIS',
    'Pawon forms part of the Buddhist heritage route connecting Mendut and Borobudur. Behave quietly, dress respectfully and avoid touching carvings or disrupting religious activities. Damaging, climbing or removing any part of the protected monument is prohibited.',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Gudeg, Bakpia',
    'Hotel',
    'Car',
    'Rp600,000',
    '08:00–17:00',
    '',
    'Borobudur Health Centre (Puskesmas)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Borobudur Market'
  ),
  'indonesia-prambanan': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Prambanan is a Hindu temple complex associated with the Ramayana tradition and ancient Javanese Hindu heritage. Dress modestly, respect worship and performances and avoid climbing or touching fragile structures. Remain within public areas, obey monument closures and do not vandalise, remove stones or use restricted drones.',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Gudeg, Bakpia',
    'Hotel',
    'Car',
    'Rp700,000',
    '06:30–17:00',
    '',
    'Yogyakarta Regional Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Prambanan Market, Indomaret'
  ),
  'indonesia-dieng': R(
    'Cash (IDR), QRIS',
    'The Dieng temples reflect ancient Javanese Hindu heritage and local traditions such as the Dieng Culture Festival. Respect rituals, ask before photographing participants and avoid disrupting ceremonies or touching temple structures. Do not climb or damage monuments; obey geothermal hazard barriers, conservation rules and temporary weather closures.',
    'Warm jacket, comfortable shoes',
    'Walking',
    'Mie Ongklok, Tempe Kemul',
    'Hotel',
    'Car',
    'Rp700,000',
    '07:00–17:00',
    '',
    'Wonosobo Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Wonosobo Market, Indomaret'
  ),
  'indonesia-gunungpadang': R(
    'Cash (IDR), QRIS',
    'The megalithic site is connected to Sundanese history, oral traditions and local beliefs. Use established paths, respect guides and residents and avoid treating stones as seats or play structures. Do not move, carve, climb irresponsibly on or remove archaeological stones; follow protected-site access restrictions.',
    'Comfortable outdoor clothing, closed-toe shoes',
    'Walking',
    'Nasi Liwet Sunda, Tauco',
    'Hotel',
    'Car',
    'Rp700,000',
    '08:00–17:00',
    '',
    'Cianjur Regional Hospital',
    'Groundwater, Bottled Water',
    'Cianjur Market'
  ),
  'indonesia-sangiran': R(
    'Cash (IDR), QRIS',
    'Sangiran preserves prehistoric human history and is an important scientific and educational heritage landscape. Respect museum displays, local fossil-related heritage and village property; ask before photographing residents. Removing, purchasing or exporting protected fossils and archaeological objects without authorisation is prohibited.',
    'Comfortable casual clothing',
    'Walking',
    'Timlo Solo, Selat Solo',
    'Hotel',
    'Car',
    'Rp700,000',
    '08:00–16:00',
    '',
    'Sragen Regional Hospital',
    'Groundwater, Bottled Water',
    'Gemolong Market'
  ),
  'indonesia-badavalley': R(
    'Cash (IDR)',
    'The valley contains ancient megaliths and communities with distinctive Central Sulawesi traditions and crafts. Use local guides, ask permission before entering traditional spaces and do not touch or climb megaliths. Do not remove, move, mark or damage archaeological objects; follow Lore Lindu National Park regulations.',
    'Comfortable outdoor clothing, hiking shoes',
    'Walking',
    'Kaledo, Uta Dada',
    'Guesthouse, Homestay',
    'Plane, Car',
    'Rp900,000',
    '08:00–17:00',
    '',
    'Poso Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Poso Market'
  ),
  'indonesia-trowulan': R(
    'Cash (IDR), QRIS',
    'Trowulan is associated with the Majapahit Empire and Javanese historical identity. Dress respectfully at temples and sacred graves, speak quietly and avoid climbing ruins. Damaging, removing or altering bricks, statues and archaeological material is prohibited under heritage protections.',
    'Comfortable casual clothing',
    'Walking',
    'Rawon, Rujak Cingur',
    'Hotel',
    'Car',
    'Rp700,000',
    '08:00–16:00',
    '',
    'Mojokerto Regional Hospital',
    'Groundwater, Bottled Water',
    'Mojokerto Market, Indomaret'
  ),
  'indonesia-gunungkawi': R(
    'Cash (IDR), QRIS',
    'Gunung Kawi contains Balinese Hindu rock-cut shrines, holy-water sites and living religious traditions. Wear a sarong and sash, respect purification rituals and avoid entering worship areas during ceremonies without permission. Do not damage carvings, enter closed sacred zones, pollute holy water or behave disrespectfully at shrines.',
    'Modest clothing; sarong for shrine areas',
    'Walking',
    'Babi Guling, Lawar',
    'Hotel, Villa',
    'Car',
    'Rp900,000',
    '08:00–17:00',
    '',
    'Bangli Regional Hospital',
    'Holy Spring Water, Bottled Water',
    'Ubud Market, Coco Supermarket'
  ),
  'indonesia-muaroajambi': R(
    'Cash (IDR), QRIS',
    'The complex reflects ancient Buddhist learning and Malay-Jambi heritage along the Batang Hari River. Dress modestly, cycle carefully, respect villages and avoid climbing fragile brick structures. Do not remove bricks or artefacts, excavate, vandalise or enter restricted archaeological areas.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Tempoyak, Gulai Ikan',
    'Hotel',
    'Plane, Car',
    'Rp800,000',
    '08:00–17:00',
    '',
    'Jambi Regional Hospital',
    'River Water, Bottled Water',
    'Jambi City Mall, Jambi Town Square'
  ),
  'indonesia-waerebo': R(
    'Cash (IDR)',
    'Wae Rebo is a Manggarai cultural village known for Mbaru Niang houses, communal life and traditional ceremonies. Attend the customary welcome process, follow local hosts, dress respectfully and ask before photographing people or homes. Do not enter houses or sacred areas without permission, use drones without approval or damage village property.',
    'Modest clothing, comfortable walking shoes',
    'Walking',
    'Se\'i Sapi, Flores Coffee',
    'Homestay',
    'Plane, Car',
    'Rp700,000',
    'Open 24 Hours',
    '',
    'Ruteng Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Dintor Village Shops'
  ),
  'indonesia-kotatua': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The district reflects Jakarta\'s colonial, Betawi, Chinese-Indonesian and maritime history. Respect museums, street performers and worship sites; ask before photographing individuals. Do not vandalise protected buildings, climb monuments, litter or enter restricted structures.',
    'Light casual clothing, comfortable shoes',
    'Walking',
    'Kerak Telor, Soto Betawi',
    'Hotel',
    'Car',
    'Rp800,000',
    '08:00–21:00',
    '',
    'Tarakan Regional Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Pasar Asemka, Indomaret'
  ),
  'indonesia-tamansari': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Taman Sari reflects the history of the Yogyakarta Sultanate, Javanese court culture and royal architecture. Dress respectfully, avoid blocking narrow passages and behave appropriately near residential and religious areas. Do not climb, carve or damage heritage structures; enter underground areas only through authorised routes.',
    'Modest clothing, comfortable walking shoes',
    'Walking',
    'Gudeg, Bakpia',
    'Hotel',
    'Car',
    'Rp700,000',
    '09:00–17:00',
    '',
    'PKU Muhammadiyah Hospital Yogyakarta',
    'Tap Water (Not Drinkable), Bottled Water',
    'Malioboro Shops, Indomaret'
  ),
  'indonesia-tanatoraja': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'Torajan culture includes tongkonan houses, elaborate funeral rituals, ancestral traditions and distinctive burial sites. Use local guides, ask before attending or photographing ceremonies and never touch graves, effigies or offerings. Do not enter ritual areas or burial chambers without permission, damage graves or remove cultural objects.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Pa\'piong, Deppa Tori',
    'Homestay',
    'Plane, Car',
    'Rp1,000,000',
    'Open 24 Hours',
    '',
    'Lakipadada Hospital (Makale)',
    'Mountain Spring, Bottled Water',
    'Makale Market'
  ),
  'indonesia-wukirsari': R(
    'Cash (IDR), QRIS',
    'The village is known for Javanese batik, leather puppetry, craft traditions and community-based tourism. Greet artisans politely, ask before photographing workshops and handle batik and puppets only with permission. Do not copy, remove or damage workshop materials; follow village environmental and plastic-reduction rules.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Gudeg, Jamu',
    'Homestay',
    'Car',
    'Rp700,000',
    '08:00–17:00',
    '',
    'Bantul Regional Hospital',
    'Groundwater, Bottled Water',
    'Bantul Market'
  ),
  'indonesia-ubudtegalalang': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The area combines Balinese Hindu temples, arts, dance, farming traditions and the subak irrigation landscape. Wear temple clothing where required, do not step on offerings and avoid entering or damaging working rice fields. Stay on authorised paths, pay required access fees and do not trespass, litter or fly drones in restricted areas.',
    'Light casual clothing, comfortable sandals',
    'Walking',
    'Babi Guling, Bebek Betutu',
    'Hotel, Villa',
    'Car',
    'Rp1,500,000',
    'Open 24 Hours',
    '',
    'Ubud Care Clinic',
    'Tap Water (Not Drinkable), Bottled Water',
    'Ubud Market, Coco Supermarket'
  ),
  'indonesia-rajaampatresorts': R(
    'Credit/Debit Card, Bank Transfer',
    'The resort operates near Papuan island communities and environmentally sensitive reefs. Respect staff and neighbouring communities, conserve water and avoid touching coral or marine animals. Follow resort dive and marine-park rules; do not collect marine life, fish without permission or damage reefs.',
    'Resort wear, reef-safe swimwear',
    'Boat, Kayak',
    'Fresh Seafood, Papeda',
    'Eco Resort',
    'Plane, Boat',
    'Rp4,000,000',
    'Open 24 Hours',
    '',
    'Raja Ampat Regional Hospital (Waisai)',
    'Rainwater Collection, Bottled Water',
    'Resort Boutique Shop'
  ),
  'indonesia-misool': R(
    'Credit/Debit Card, Bank Transfer',
    'The resort is closely linked to marine conservation and local Papuan community partnerships. Follow conservation briefings, avoid single-use waste and maintain distance from reefs and wildlife. No-take-zone rules prohibit fishing and marine extraction; guests must obey dive, boating and protected-area regulations.',
    'Resort wear, reef-safe swimwear',
    'Boat, Kayak',
    'Fresh Seafood, Papeda',
    'Eco Resort',
    'Plane, Boat',
    'Rp4,500,000',
    'Open 24 Hours',
    '',
    'Raja Ampat Regional Hospital (Waisai)',
    'Rainwater Collection, Bottled Water',
    'Resort Boutique Shop'
  ),
  'indonesia-riauoverwater': R(
    'Credit/Debit Card, Bank Transfer',
    'The resort reflects Malay island hospitality and the culture of nearby fishing communities. Dress respectfully when visiting villages, conserve resources and ask before photographing residents. Follow resort water-safety rules; do not litter, damage mangroves or enter village and marine areas without permission.',
    'Resort casual wear',
    'Walking, Bicycle',
    'Gonggong, Fresh Seafood',
    'Beach Resort',
    'Plane, Ferry',
    'Rp3,500,000',
    'Open 24 Hours',
    '',
    'Batam Regional Hospital',
    'Fresh Water Supply, Bottled Water',
    'Resort Convenience Store'
  ),
  'indonesia-bawah': R(
    'Credit/Debit Card, Bank Transfer',
    'The reserve combines Riau Malay island surroundings with luxury conservation-focused tourism. Follow sustainability guidelines, conserve water, respect staff and avoid disturbing marine habitats. Do not fish, collect shells or coral, damage reefs or enter protected zones without authorisation.',
    'Resort casual wear',
    'Walking, Bicycle',
    'Fresh Seafood, Laksa Kepulauan Riau',
    'Luxury Eco Resort',
    'Plane, Seaplane',
    'Rp8,000,000',
    'Open 24 Hours',
    '',
    'Batam Regional Hospital',
    'Rainwater Collection, Bottled Water',
    'Resort Boutique Shop'
  ),
  'indonesia-cirata': R(
    'Cash (IDR), QRIS',
    'The floating settlement reflects Sundanese reservoir culture, aquaculture and fishing-based livelihoods. Respect homes and fish cages, ask before photographing residents and avoid blocking boats or work areas. Use safe authorised boats, do not enter restricted reservoir infrastructure or interfere with aquaculture equipment.',
    'Comfortable casual clothing, sandals',
    'Boat',
    'Nasi Liwet Sunda, Ikan Bakar',
    'Homestay',
    'Car, Boat',
    'Rp700,000',
    'Open 24 Hours',
    '',
    'Cianjur Regional Hospital',
    'Reservoir Water, Bottled Water',
    'Jangari Floating Market'
  ),
  'indonesia-penglipuran': R(
    'Cash (IDR), Credit/Debit Card, QRIS',
    'The village preserves Balinese architecture, the Tri Mandala spatial concept, communal traditions and local cuisine. Dress modestly, do not enter private compounds without permission and respect temples, offerings and ceremonies. Follow village cleanliness rules; do not damage traditional buildings, litter or enter sacred areas improperly.',
    'Modest casual clothing',
    'Walking',
    'Lawar, Tipat Cantok',
    'Homestay',
    'Car',
    'Rp800,000',
    '08:00–17:00',
    '',
    'Bangli Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Penglipuran Village Shops'
  ),
  'indonesia-waerebohistorical': R(
    'Cash (IDR)',
    'The village preserves Manggarai communal traditions, Mbaru Niang houses, weaving, coffee and customary hospitality. Complete the customary welcome, follow village elders and ask before photographing or entering houses. Do not use drones, enter sacred areas or stay overnight without required village permission and arrangements.',
    'Modest clothing, comfortable walking shoes',
    'Walking',
    'Se\'i Sapi, Flores Coffee',
    'Homestay',
    'Plane, Car',
    'Rp700,000',
    'Open 24 Hours',
    '',
    'Ruteng Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Dintor Village Shops'
  ),
  'indonesia-tenganan': R(
    'Cash (IDR), QRIS',
    'The Bali Aga village is known for Gringsing double-ikat weaving and rituals such as Perang Pandan. Dress respectfully, follow ceremony instructions and ask before photographing weaving, rituals or residents. Do not interrupt rituals, enter restricted sacred spaces or remove cultural and sacred objects.',
    'Modest casual clothing',
    'Walking',
    'Lawar, Jaje Bali',
    'Homestay',
    'Car',
    'Rp800,000',
    '08:00–17:00',
    '',
    'Bangli Regional Hospital',
    'Mountain Spring, Bottled Water',
    'Tenganan Village Shops'
  ),
  'indonesia-sukararasade': R(
    'Cash (IDR), QRIS',
    'The Sasak village is known for traditional weaving, ceremonial textiles and women\'s craft knowledge. Ask before photographing weavers, handle textiles carefully and dress respectfully when entering homes. Do not enter private workshops without permission or remove designs, tools or products without payment.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Ayam Taliwang, Plecing Kangkung',
    'Homestay',
    'Plane, Car',
    'Rp700,000',
    '08:00–17:00',
    '',
    'Praya Regional Hospital',
    'Groundwater, Bottled Water',
    'Sukarara Weaving Shops'
  ),
  'indonesia-sade': R(
    'Cash (IDR), QRIS',
    'Sade preserves Sasak houses, weaving traditions, customary social life and traditional architecture. Use local guides, ask before entering homes or photographing residents and dress modestly. Do not damage traditional houses, enter private spaces without permission or remove cultural objects.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Ayam Taliwang, Plecing Kangkung',
    'Homestay',
    'Plane, Car',
    'Rp700,000',
    '08:00–17:00',
    '',
    'Praya Regional Hospital',
    'Groundwater, Bottled Water',
    'Sade Village Souvenir Shops'
  ),
  'indonesia-prailirende': R(
    'Cash (IDR)',
    'The village is known for Sumbanese ikat weaving, traditional houses, megalithic tombs and Marapu-influenced traditions. Ask before photographing people, tombs or ceremonies and never stand or sit on ancestral graves. Do not damage or remove textiles, grave objects, megaliths or sacred items; obey customary restrictions.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Kaparak, Kambaniru Fish',
    'Homestay',
    'Plane, Car',
    'Rp650,000',
    '08:00–17:00',
    '',
    'Waingapu Regional Hospital',
    'Groundwater, Bottled Water',
    'Waingapu Market'
  ),
  'indonesia-rende': R(
    'Cash (IDR)',
    'Rende preserves Sumbanese royal history, traditional houses, stone tombs, ikat and Marapu-related practices. Use a local guide, dress respectfully and ask permission before approaching tombs, houses or ceremonies. Do not climb tombs, touch sacred objects or enter customary spaces without approval.',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Kaparak, Kambaniru Fish',
    'Homestay',
    'Plane, Car',
    'Rp650,000',
    '08:00–17:00',
    '',
    'Waingapu Regional Hospital',
    'Groundwater, Bottled Water',
    'Indomaret, Alfamart'
  ),
  'indonesia-giriloyo': R(
    'Cash (IDR), QRIS',
    'Giriloyo is a Javanese artisan village known for hand-drawn batik and skills passed through generations. Respect artisans\' working time, ask before photographing designs and follow workshop instructions carefully. Do not take tools, cloth or designs without permission; follow workshop safety and waste-disposal requirements.',
    'Comfortable casual clothing',
    'Walking',
    'Gudeg, Bakpia',
    'Hotel',
    'Car',
    'Rp700,000',
    '08:00–17:00',
    '',
    'Bantul Regional Hospital',
    'Groundwater, Bottled Water',
    'Bantul Market'
  ),
};

// Base fields for brand-new Indonesia places
const IND_NEW_BASE = {
  'indonesia-mendut': {
    country: 'Indonesia',
    category: 'Ancient ruins',
    location: 'Mendut Temple',
    primaryActivities: 'Ancient Buddhist temple; Vesak procession start point',
    howToGetThere: 'Fly SIN → JOG or CGK; road to the Borobudur plain (Mendut is ~3 km east of Borobudur)',
    visaEntry: 'Visa‑free up to 30 days or eVOA up to 60 days (extendable)',
    accessNeeded: 'Entrance ticket; remove shoes near prayer areas',
    navigationTips: 'Google Maps; combine with Borobudur and Pawon',
  },
  'indonesia-pawon': {
    country: 'Indonesia',
    category: 'Ancient ruins',
    location: 'Pawon Temple',
    primaryActivities: 'Ancient Buddhist temple on the Borobudur heritage route',
    howToGetThere: 'Fly SIN → JOG or CGK; road to the Borobudur plain (Pawon sits between Mendut and Borobudur)',
    visaEntry: 'Visa‑free up to 30 days or eVOA up to 60 days (extendable)',
    accessNeeded: 'Entrance ticket',
    navigationTips: 'Google Maps; combine with Borobudur and Mendut',
  },
  'indonesia-misool': {
    country: 'Indonesia',
    category: 'Coastline/islands',
    location: 'Misool Eco Resort (Raja Ampat)',
    primaryActivities: 'Overwater eco resort; diving and snorkeling',
    howToGetThere: 'Fly SIN → CGK/UPG → Sorong (SOQ); speedboat transfer to Misool',
    visaEntry: 'Visa‑free up to 30 days or eVOA up to 60 days (extendable)',
    accessNeeded: 'Resort booking; dive/marine-park fees',
    navigationTips: 'Resort handles transfers and navigation',
  },
  'indonesia-bawah': {
    country: 'Indonesia',
    category: 'Coastline/islands',
    location: 'Bawah Reserve (Riau Islands)',
    primaryActivities: 'Luxury eco resort on private islands; snorkeling and kayaking',
    howToGetThere: 'Fly SIN → Batam (BTH); seaplane or boat transfer',
    visaEntry: 'Visa‑free up to 30 days or eVOA up to 60 days (extendable)',
    accessNeeded: 'Resort booking; seaplane/boat transfer',
    navigationTips: 'Resort coordinates transfers',
  },
  'indonesia-sade': {
    country: 'Indonesia',
    category: 'Cultural villages',
    location: 'Sade Village (Central Lombok)',
    primaryActivities: 'Traditional Sasak village; weaving and architecture',
    howToGetThere: 'Fly SIN → Lombok (LOP) or DPS; road to central Lombok',
    visaEntry: 'Visa‑free up to 30 days or eVOA up to 60 days (extendable)',
    accessNeeded: 'Local guide/transport; modest dress',
    navigationTips: 'Local guides; Google Maps to Sade',
  },
  'indonesia-rende': {
    country: 'Indonesia',
    category: 'Cultural villages',
    location: 'Rende Village (East Sumba)',
    primaryActivities: 'Sumbanese royal village; ikat weaving; megalithic tombs',
    howToGetThere: 'Fly SIN → DPS/CGK → Waingapu (WGP); road to village',
    visaEntry: 'Visa‑free up to 30 days or eVOA up to 60 days (extendable)',
    accessNeeded: 'Local guide; dress respectfully',
    navigationTips: 'Local guides; offline maps',
  },
};

// Rename combined places to their split destinations
const IND_RENAME = {
  'indonesia-rajaampatresorts': 'Papua Paradise Eco Resort (Raja Ampat)',
  'indonesia-riauoverwater': 'Telunas Beach Resort (Riau Islands)',
  'indonesia-sukararasade': 'Sukarara Village (Central Lombok)',
  'indonesia-prailirende': 'Prailiu Village (East Sumba)',
};

// ---------------------------------------------------------------------------
// CAMBODIA
// ---------------------------------------------------------------------------
const KHM = {
  'cambodia-kohrong': R(
    'Cash (KHR/USD), Credit/Debit Card',
    'Respect local fishing communities',
    'Light beachwear, casual clothing',
    'Walking, Scooter, Tuk-tuk',
    'Fresh Seafood, Fish Amok',
    'Beach Resort, Hotel, Hostel',
    'Ferry, Speedboat',
    'US$80',
    'Open 24 Hours',
    'Emergency Services Police: 117 Fire: 118 Ambulance: 119 Tourist Police (English): 077 788 603 Country Code: +855',
    'Koh Rong Clinic',
    'Rainwater Collection, Bottled Water',
    'Village Shops, Mini Mart'
  ),
  'cambodia-kohatang': R(
    'Cash (KHR/USD)',
    'Respect marine conservation rules',
    'Light beachwear, reef-safe swimwear',
    'Boat, Kayak',
    'Fresh Seafood, Grilled Squid',
    'Eco Resort, Liveaboard',
    'Boat',
    'US$180',
    '08:00–17:00',
    '',
    'Sihanoukville Provincial Referral Hospital',
    'Rainwater Collection, Bottled Water',
    'Sihanoukville Supermarket'
  ),
  'cambodia-tonlesapflooded': R(
    'Cash (KHR/USD)',
    'Respect wildlife and local communities',
    'Light clothing, comfortable walking shoes',
    'Boat',
    'Fish Amok, Grilled Fish',
    'Floating Lodge, Eco Lodge',
    'Car, Boat',
    'US$70',
    '07:00–17:00',
    '',
    'Pursat Provincial Hospital',
    'Lake Water, Bottled Water',
    'Pursat Market'
  ),
  'cambodia-kohrongmarine': R(
    'Cash (KHR/USD), Credit/Debit Card',
    'Do not touch coral or marine life',
    'Swimwear, reef-safe clothing',
    'Boat, Snorkeling Boat',
    'Fresh Seafood, Fish Amok',
    'Beach Resort, Liveaboard',
    'Ferry, Speedboat',
    'US$180',
    '08:00–17:00',
    '',
    'Koh Rong Clinic',
    'Rainwater Collection, Bottled Water',
    'Village Shops, Mini Mart'
  ),
  'cambodia-sangkaeriver': R(
    'Cash (KHR/USD)',
    'Dress modestly in local villages',
    'Light casual clothing',
    'Walking, Tuk-tuk',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$50',
    'Open 24 Hours',
    '',
    'Battambang Provincial Referral Hospital',
    'River Water, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-kampingpuoy': R(
    'Cash (KHR/USD)',
    'Keep reservoir clean; respect locals',
    'Light casual clothing, hat',
    'Walking, Bicycle',
    'Lotus Stem Salad, Grilled Fish',
    'Hotel, Resort',
    'Car',
    'US$45',
    '06:00–18:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Reservoir Water, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-prektoal': R(
    'Cash (KHR/USD)',
    'Observe birds quietly; no littering',
    'Light outdoor clothing',
    'Boat',
    'Fresh Fish, Fish Amok',
    'Eco Lodge, Homestay',
    'Boat',
    'US$90',
    '07:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Lake Water, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-cardamommountains': R(
    'Cash (KHR/USD)',
    'Respect indigenous communities',
    'Light hiking clothing',
    '4WD, Hiking',
    'Prahok Ktis, Samlor Korkor',
    'Eco Lodge, Camping',
    'Car',
    'US$60',
    '07:00–17:00',
    '',
    'Pursat Provincial Hospital',
    'Mountain Streams, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-samlautusearea': R(
    'Cash (KHR/USD)',
    'Stay on designated trails',
    'Light hiking clothing',
    '4WD, Hiking',
    'Prahok Ktis, Fish Amok',
    'Eco Lodge, Homestay',
    'Car',
    'US$70',
    '07:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'River Water, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-phnomsampeou': R(
    'Cash (KHR/USD)',
    'Dress modestly at temples',
    'Comfortable walking shoes',
    'Walking',
    'Num Banh Chok, Grilled Chicken',
    'Hotel, Guesthouse',
    'Car',
    'US$40',
    '07:00–18:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-phnomsampeoucaves': R(
    'Cash (KHR/USD)',
    'Dress modestly; speak quietly',
    'Comfortable clothing, closed-toe shoes',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-pkaslacave': R(
    'Cash (KHR/USD)',
    'Do not damage cave formations',
    'Comfortable clothing, closed-toe shoes',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-lakhoncave': R(
    'Cash (KHR/USD)',
    'Respect sacred cave sites',
    'Comfortable clothing, closed-toe shoes',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-yeaklaom': R(
    'Cash (KHR/USD)',
    'Respect local customs',
    'Modest swimwear, comfortable clothing',
    'Walking',
    'Bamboo Sticky Rice, Fish Amok',
    'Hotel, Eco Lodge',
    'Car',
    'US$50',
    '06:00–18:00',
    '',
    'Banlung Provincial Referral Hospital',
    'Volcanic Lake, Bottled Water',
    'Banlung Market'
  ),
  'cambodia-bousra': R(
    'Cash (KHR/USD)',
    'Respect indigenous Bunong culture',
    'Light hiking clothing',
    '4WD, Hiking',
    'Grilled Chicken, Bamboo Sticky Rice',
    'Eco Lodge, Homestay',
    'Car',
    'US$55',
    'Open 24 Hours',
    '',
    'Mondulkiri Provincial Referral Hospital',
    'Mountain Spring, Bottled Water',
    'Sen Monorom Market'
  ),
  'cambodia-cardamomhighlands': R(
    'Cash (KHR/USD)',
    'Leave no trace while hiking',
    'Light hiking clothing',
    '4WD, Hiking',
    'Fish Amok, Samlor Korkor',
    'Eco Lodge, Resort',
    'Car',
    'US$60',
    'Open 24 Hours',
    '',
    'Pursat Provincial Hospital',
    'Mountain Spring, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-battambangkarst': R(
    'Cash (KHR/USD)',
    'Do not climb fragile rock formations',
    'Comfortable outdoor clothing',
    'Walking',
    'Num Banh Chok, Prahok Ktis',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    'Open 24 Hours',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-phnomkrapeu': R(
    'Cash (KHR/USD)',
    'Dress respectfully at sacred sites',
    'Comfortable outdoor clothing',
    'Walking',
    'Num Banh Chok, Grilled Chicken',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '07:00–18:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-phnomsampeoucliffs': R(
    'Cash (KHR/USD)',
    'Respect temple grounds',
    'Comfortable outdoor clothing',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '07:00–18:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-samlautrainforest': R(
    'Cash (KHR/USD)',
    'Leave no trace in rainforest',
    'Light hiking clothing',
    'Hiking',
    'Samlor Korkor, Bamboo Sticky Rice',
    'Eco Lodge, Camping',
    'Car',
    'US$60',
    '07:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'River Water, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-cardamomrainforest': R(
    'Cash (KHR/USD)',
    'Respect wildlife; no feeding animals',
    'Light hiking clothing',
    'Hiking',
    'Fish Amok, Prahok Ktis',
    'Eco Lodge, Resort',
    'Car',
    'US$70',
    '07:00–17:00',
    '',
    'Pursat Provincial Hospital',
    'River Water, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-preylang': R(
    'Cash (KHR/USD)',
    'Respect protected forests',
    'Light hiking clothing',
    'Hiking',
    'Samlor Korkor, Num Banh Chok',
    'Eco Lodge, Camping',
    'Car',
    'US$55',
    '07:00–17:00',
    '',
    'Stung Treng Provincial Referral Hospital',
    'Forest Streams, Bottled Water',
    'Stung Treng Market'
  ),
  'cambodia-angtrapaengthmor': R(
    'Cash (KHR/USD)',
    'Observe cranes quietly; keep distance',
    'Light outdoor clothing',
    'Boat',
    'Fish Amok, Lotus Stem Salad',
    'Eco Lodge, Homestay',
    'Car',
    'US$50',
    '07:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Wetland Water, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-watbanan': R(
    'Cash (KHR/USD)',
    'Dress modestly at temples',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Num Banh Chok, Khmer Curry',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '07:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-watekphnom': R(
    'Cash (KHR/USD)',
    'Dress modestly at temples',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '07:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-banteaychhmar': R(
    'Cash (KHR/USD)',
    'Respect historical monuments',
    'Modest clothing; shoulders and knees covered',
    'Walking',
    'Khmer Curry, Beef Lok Lak',
    'Hotel, Guesthouse',
    'Car',
    'US$40',
    '07:00–17:00',
    '',
    'Banteay Meanchey Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Sisophon Central Market'
  ),
  'cambodia-killingcaves': R(
    'Cash (KHR/USD)',
    'Maintain silence at memorial sites',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Num Banh Chok, Grilled Chicken',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-watsamrongknong': R(
    'Cash (KHR/USD)',
    'Dress modestly at pagodas',
    'Modest clothing, comfortable shoes',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-frenchcolonial': R(
    'Cash (KHR/USD), Credit/Debit Card',
    'Respect colonial heritage buildings',
    'Casual clothing, comfortable shoes',
    'Walking',
    'Beef Lok Lak, Kuy Teav',
    'Hotel, Boutique Hotel',
    'Car',
    'US$50',
    'Open 24 Hours',
    '',
    'Battambang Provincial Referral Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Lucky Supermarket Battambang'
  ),
  'cambodia-watkor': R(
    'Cash (KHR/USD)',
    'Respect traditional village lifestyle',
    'Modest casual clothing',
    'Walking, Bicycle',
    'Num Banh Chok, Fish Amok',
    'Homestay',
    'Car',
    'US$30',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-sangkaecountryside': R(
    'Cash (KHR/USD)',
    'Ask permission before photographing locals',
    'Comfortable casual clothing',
    'Bicycle, Car',
    'Num Banh Chok, Grilled Chicken',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    'Open 24 Hours',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-ricefieldvillages': R(
    'Cash (KHR/USD)',
    'Respect residents\' privacy',
    'Light casual clothing',
    'Walking, Bicycle',
    'Sticky Rice, Grilled Fish',
    'Homestay',
    'Car',
    'US$30',
    'Open 24 Hours',
    '',
    'Pursat Provincial Hospital',
    'Lake Water, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-kompongluong': R(
    'Cash (KHR/USD)',
    'Respect floating village communities',
    'Light casual clothing',
    'Boat',
    'Fresh Fish, Fish Amok',
    'Homestay',
    'Boat',
    'US$40',
    '06:00–18:00',
    '',
    'Pursat Provincial Hospital',
    'Lake Water, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-chongkos': R(
    'Cash (KHR/USD)',
    'Respect floating village communities',
    'Light casual clothing',
    'Boat',
    'Fresh Fish, Prahok',
    'Homestay',
    'Boat',
    'US$40',
    '06:00–18:00',
    '',
    'Pursat Provincial Hospital',
    'Lake Water, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-phoumkandal': R(
    'Cash (KHR/USD)',
    'Support local livelihoods',
    'Light casual clothing',
    'Boat',
    'Fresh Fish, Grilled Fish',
    'Homestay',
    'Boat',
    'US$40',
    '06:00–18:00',
    '',
    'Pursat Provincial Hospital',
    'Groundwater, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-watkorheritage': R(
    'Cash (KHR/USD)',
    'Dress modestly in heritage village',
    'Modest casual clothing',
    'Walking',
    'Num Banh Chok, Fish Amok',
    'Homestay',
    'Car',
    'US$30',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-phareponleu': R(
    'Cash (KHR/USD)',
    'Support local artists and performers',
    'Comfortable casual clothing',
    'Walking',
    'Khmer BBQ, Fish Amok',
    'Hotel, Guesthouse',
    'Car',
    'US$35',
    '09:00–20:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-bananpottery': R(
    'Cash (KHR/USD)',
    'Support local craftsmen',
    'Comfortable casual clothing',
    'Walking',
    'Rice Cakes, Khmer Desserts',
    'Homestay',
    'Car',
    'US$30',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Battambang Central Market'
  ),
  'cambodia-battambangartisan': R(
    'Cash (KHR/USD), Credit/Debit Card',
    'Respect local businesses',
    'Casual clothing, comfortable shoes',
    'Walking, Tuk-tuk',
    'Beef Lok Lak, Fish Amok',
    'Hotel, Boutique Hotel',
    'Car',
    'US$50',
    'Open 24 Hours',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Lucky Supermarket Battambang'
  ),
  'cambodia-pursatmarble': R(
    'Cash (KHR/USD)',
    'Support local artisans',
    'Comfortable casual clothing',
    'Walking',
    'Rice Cakes, Fish Amok',
    'Homestay',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Pursat Provincial Hospital',
    'Groundwater, Bottled Water',
    'Pursat Central Market'
  ),
  'cambodia-roluos': R(
    'Cash (KHR/USD)',
    'Respect pottery-making traditions',
    'Comfortable casual clothing',
    'Walking',
    'Rice Cakes, Num Banh Chok',
    'Homestay',
    'Car',
    'US$35',
    '08:00–17:00',
    '',
    'Battambang Provincial Referral Hospital',
    'Groundwater, Bottled Water',
    'Battambang Central Market'
  ),
};

// ---------------------------------------------------------------------------
// VIETNAM
// ---------------------------------------------------------------------------
const VNM = {
  'vietnam-halongbay': R(
    'Cash (VND), Credit/Debit Card',
    'Respect marine conservation rules',
    'Casual, Beachwear',
    'Cruise Boat',
    'Cha Muc, Fresh Seafood',
    'Cruise, Hotel',
    'Cruise',
    'US$90–180',
    'Open 24 Hours',
    'Emergency Services Police: 113 Fire: 114 Ambulance: 115 Search & Rescue: 112 Country Code: +84',
    'Bai Chay Hospital (Ha Long)',
    'Rainwater Collection, Bottled Water',
    'Rainwater Collection, Bottled Water'
  ),
  'vietnam-condao-islands': R(
    'Cash (VND), Credit/Debit Card',
    'Respect sea turtle nesting areas',
    'Casual, Beachwear',
    'Walking, Bicycle',
    'Fresh Seafood, Grilled Squid',
    'Beach Resort, Eco Resort',
    'Plane, Ferry',
    'US$80–180',
    'Open 24 Hours',
    '',
    'Con Dao Medical Center',
    'Rainwater Collection, Bottled Water',
    'Rainwater Collection, Bottled Water'
  ),
  'vietnam-phuquoc': R(
    'Cash (VND), Credit/Debit Card',
    'Dress modestly in local communities',
    'Casual, Beachwear',
    'Motorbike, Taxi',
    'Bun Quay, Fresh Seafood',
    'Beach Resort, Hotel',
    'Plane, Ferry',
    'US$60–150',
    'Open 24 Hours',
    '',
    'Phu Quoc General Hospital',
    'Groundwater, Bottled Water',
    'Groundwater, Bottled Water'
  ),
  'vietnam-honmun': R(
    'Cash (VND), Credit/Debit Card',
    'Do not touch coral or marine life',
    'Swimwear, Rash Guard',
    'Boat',
    'Fresh Seafood, Bun Cha Ca',
    'Resort, Dive Lodge',
    'Car, Boat',
    'US$50–120',
    '08:00–17:00',
    '',
    'Nha Trang General Hospital',
    'Sea Water, Bottled Water',
    'Sea Water, Bottled Water'
  ),
  'vietnam-culaocham': R(
    'Cash (VND), Credit/Debit Card',
    'Respect marine protected areas',
    'Swimwear, Rash Guard',
    'Boat',
    'Cao Lau, Mi Quang',
    'Beach Resort, Hotel',
    'Car, Boat',
    'US$50–120',
    '08:00–17:00',
    '',
    'Hoi An Hospital',
    'Sea Water, Bottled Water',
    'Sea Water, Bottled Water'
  ),
  'vietnam-condao-nationalpark': R(
    'Cash (VND), Credit/Debit Card',
    'Protect turtles; do not disturb wildlife',
    'Swimwear, Outdoor Wear',
    'Boat',
    'Fresh Seafood, Goi Ca Mai',
    'Eco Lodge, Resort',
    'Plane, Boat',
    'US$80–180',
    '08:00–17:00',
    '',
    'Con Dao Medical Center',
    'Rainwater Collection, Bottled Water',
    'Rainwater Collection, Bottled Water'
  ),
  'vietnam-tramchim': R(
    'Cash (VND), QR Payment',
    'Observe wildlife quietly; no littering',
    'Light Outdoor Clothing',
    'Boat, Walking',
    'Com Tam, Grilled Snakehead Fish',
    'Eco Lodge, Homestay',
    'Car',
    'US$40–80',
    '07:00–17:00',
    '',
    'Tam Nong District Hospital',
    'Wetland Water, Bottled Water',
    'Wetland Water, Bottled Water'
  ),
  'vietnam-vanlong': R(
    'Cash (VND), QR Payment',
    'Stay on designated waterways',
    'Light Outdoor Clothing',
    'Boat',
    'Com Chay, Goat Meat',
    'Eco Lodge, Homestay',
    'Car',
    'US$35–70',
    '07:00–17:00',
    '',
    'Ninh Binh General Hospital',
    'Wetland Water, Bottled Water',
    'Wetland Water, Bottled Water'
  ),
  'vietnam-mekongdelta': R(
    'Cash (VND), QR Payment',
    'Respect floating market communities',
    'Light Casual Clothing',
    'Boat, Taxi',
    'Hu Tieu, Elephant Ear Fish',
    'Hotel, Homestay',
    'Car',
    'US$30–70',
    'Open 24 Hours',
    '',
    'Can Tho Central General Hospital',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-fansipan': R(
    'Cash (VND), Credit/Debit Card',
    'Dress appropriately for mountain weather',
    'Warm Hiking Clothing',
    'Cable Car, Hiking',
    'Thang Co, Thit Trau Gac Bep',
    'Mountain Lodge, Hotel',
    'Cable Car',
    'US$50–120',
    '06:00–18:00',
    '',
    'Sa Pa General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-hagiang': R(
    'Cash (VND), QR Payment',
    'Respect ethnic minority customs',
    'Hiking Clothing, Jacket',
    'Motorbike, Car',
    'Thang Co, Au Tau Porridge',
    'Homestay, Guesthouse',
    'Car',
    'US$35–80',
    'Open 24 Hours',
    '',
    'Ha Giang Provincial General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-bachma': R(
    'Cash (VND), Credit/Debit Card',
    'Leave no trace; stay on trails',
    'Hiking Clothing, Trekking Shoes',
    'Hiking',
    'Bun Bo Hue, Com Hen',
    'Eco Lodge, Resort',
    'Car',
    'US$50–100',
    '07:00–17:00',
    '',
    'Phu Loc District Medical Center',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-sondoong': R(
    'Cash (VND)',
    'Do not touch cave formations',
    'Comfortable Clothing, Non-slip Shoes',
    'Boat, Walking',
    'Pho, Grilled Pork',
    'Hotel, Lodge',
    'Car',
    'US$50–100',
    '07:30–17:00',
    '',
    'Phong Nha General Hospital',
    'Underground River, Bottled Water',
    'Underground River, Bottled Water'
  ),
  'vietnam-phongnha': R(
    'Cash (VND), Credit/Debit Card',
    'Follow boat safety rules',
    'Comfortable Clothing',
    'Boat',
    'Bun Bo Hue, Banh Beo',
    'Hotel, Resort',
    'Boat',
    'US$40–80',
    '07:30–16:30',
    '',
    'Phong Nha General Hospital',
    'Underground River, Bottled Water',
    'Underground River, Bottled Water'
  ),
  'vietnam-paradisecave': R(
    'Cash (VND), Credit/Debit Card',
    'Do not damage stalactites or stalagmites',
    'Comfortable Clothing, Non-slip Shoes',
    'Walking',
    'Bun Bo Hue, Banh Khoai',
    'Hotel, Lodge',
    'Car',
    'US$40–80',
    '07:00–17:00',
    '',
    'Phong Nha General Hospital',
    'Groundwater, Bottled Water',
    'Groundwater, Bottled Water'
  ),
  'vietnam-lyson': R(
    'Cash (VND), QR Payment',
    'Respect volcanic landscapes',
    'Casual, Sun Protection',
    'Motorbike',
    'Garlic Seafood, Sea Urchin',
    'Beach Resort, Homestay',
    'Ferry',
    'US$50–100',
    'Open 24 Hours',
    '',
    'Ly Son Military-Civilian Medical Center',
    'Groundwater, Bottled Water',
    'Groundwater, Bottled Water'
  ),
  'vietnam-bienho': R(
    'Cash (VND), QR Payment',
    'Keep crater lake clean',
    'Casual Clothing',
    'Walking',
    'Pho Kho, Bun Cua',
    'Hotel, Homestay',
    'Car',
    'US$30–60',
    'Open 24 Hours',
    '',
    'Gia Lai Provincial General Hospital',
    'Crater Lake, Bottled Water',
    'Crater Lake, Bottled Water'
  ),
  'vietnam-chudangya': R(
    'Cash (VND), QR Payment',
    'Stay on designated paths',
    'Hiking Clothing',
    'Hiking',
    'Grilled Chicken, Sticky Rice',
    'Homestay, Eco Lodge',
    'Car',
    'US$30–60',
    'Open 24 Hours',
    '',
    'Gia Lai Provincial General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-muacave': R(
    'Cash (VND), QR Payment',
    'Do not climb fragile rock formations',
    'Comfortable Outdoor Clothing',
    'Hiking',
    'Com Chay, Goat Meat',
    'Hotel, Homestay',
    'Car',
    'US$30–60',
    'Open 24 Hours',
    '',
    'Ninh Binh General Hospital',
    'Rainwater Collection, Bottled Water',
    'Rainwater Collection, Bottled Water'
  ),
  'vietnam-dongvan': R(
    'Cash (VND), QR Payment',
    'Respect UNESCO Geopark regulations',
    'Hiking Clothing',
    'Motorbike, Car',
    'Thang Co, Men Men',
    'Hotel, Homestay',
    'Car',
    'US$35–70',
    'Open 24 Hours',
    '',
    'Dong Van District General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-cattien-forest': R(
    'Cash (VND), Credit/Debit Card',
    'Do not feed wildlife',
    'Long Sleeves, Hiking Clothing',
    'Jeep, Hiking',
    'Grilled Venison, Bamboo Rice',
    'Eco Lodge, Resort',
    'Car',
    'US$50–100',
    '07:00–17:00',
    '',
    'Dong Nai General Hospital',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-yokdon': R(
    'Cash (VND)',
    'Stay on marked forest trails',
    'Long Sleeves, Hiking Clothing',
    'Jeep',
    'Grilled Beef, Bamboo Rice',
    'Eco Lodge, Camping',
    'Car',
    'US$40–80',
    '07:00–17:00',
    '',
    'Dak Lak General Hospital',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-cucphuong': R(
    'Cash (VND), QR Payment',
    'Respect protected wildlife',
    'Long Sleeves, Hiking Clothing',
    'Walking, Bicycle',
    'Mountain Goat, Com Chay',
    'Eco Lodge, Resort',
    'Car',
    'US$35–70',
    '06:00–18:00',
    '',
    'Nho Quan District General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-pumat': R(
    'Cash (VND), QR Payment',
    'Observe wildlife quietly; keep distance',
    'Long Sleeves, Hiking Clothing',
    'Jeep',
    'Eel Porridge, Grilled River Fish',
    'Eco Lodge, Homestay',
    'Car',
    'US$35–70',
    '07:00–17:00',
    '',
    'Nghe An Friendship General Hospital',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-myson': R(
    'Cash (VND), Credit/Debit Card',
    'Dress modestly at temples',
    'Modest Clothing',
    'Walking',
    'Mi Quang, Cao Lau',
    'Hotel, Resort',
    'Car',
    'US$40–80',
    '06:00–17:00',
    '',
    'Quang Nam General Hospital',
    'Groundwater, Bottled Water',
    'Groundwater, Bottled Water'
  ),
  'vietnam-trakieu': R(
    'Cash (VND), QR Payment',
    'Respect archaeological remains',
    'Modest Clothing',
    'Walking',
    'Mi Quang, Chicken Rice',
    'Hotel, Homestay',
    'Car',
    'US$30–60',
    '07:00–17:00',
    '',
    'Quang Nam General Hospital',
    'Groundwater, Bottled Water',
    'Groundwater, Bottled Water'
  ),
  'vietnam-oceo': R(
    'Cash (VND), QR Payment',
    'Do not remove historical artifacts',
    'Modest Clothing',
    'Walking',
    'Bun Mam, Grilled Fish',
    'Hotel, Homestay',
    'Car',
    'US$30–60',
    '07:00–17:00',
    '',
    'Long Xuyen General Hospital',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-hue': R(
    'Cash (VND), Credit/Debit Card',
    'Dress modestly in heritage sites',
    'Modest Clothing',
    'Walking',
    'Bun Bo Hue, Com Hen',
    'Hotel, Resort',
    'Car',
    'US$40–90',
    '08:00–17:30',
    '',
    'Hue Central Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Tap Water (Not Drinkable), Bottled Water'
  ),
  'vietnam-hoalo': R(
    'Cash (VND), Credit/Debit Card',
    'Maintain silence and respect memorials',
    'Modest Clothing',
    'Walking',
    'Pho, Bun Cha',
    'Hotel',
    'Car',
    'US$30–70',
    '08:00–17:00',
    '',
    'Saint Paul General Hospital (Hanoi)',
    'Tap Water (Not Drinkable), Bottled Water',
    'Tap Water (Not Drinkable), Bottled Water'
  ),
  'vietnam-cuchi': R(
    'Cash (VND), Credit/Debit Card',
    'Do not damage historic tunnels',
    'Comfortable Clothing',
    'Walking',
    'Banh Trang Cuon Thit Heo, Pho',
    'Hotel',
    'Car',
    'US$35–70',
    '07:00–17:00',
    '',
    'Cu Chi General Hospital',
    'Groundwater, Bottled Water',
    'Groundwater, Bottled Water'
  ),
  'vietnam-maichau': R(
    'Cash (VND), QR Payment',
    'Ask permission before photographing locals',
    'Casual, Modest Clothing',
    'Bicycle, Walking',
    'Com Lam, Grilled Chicken',
    'Homestay, Eco Lodge',
    'Car',
    'US$30–60',
    'Open 24 Hours',
    '',
    'Mai Chau District Medical Center',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-mucangchai': R(
    'Cash (VND), QR Payment',
    'Respect farming communities',
    'Casual, Sun Protection',
    'Motorbike',
    'Xoi Ngu Sac, Thang Co',
    'Homestay, Guesthouse',
    'Car',
    'US$30–60',
    'Open 24 Hours',
    '',
    'Mu Cang Chai District General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-bacson': R(
    'Cash (VND), QR Payment',
    'Stay off rice terraces',
    'Casual, Comfortable Clothing',
    'Motorbike, Bicycle',
    'Roast Duck, Sticky Rice',
    'Homestay, Guesthouse',
    'Car',
    'US$30–60',
    'Open 24 Hours',
    '',
    'Bac Son District Medical Center',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-cuavan': R(
    'Cash (VND)',
    'Respect fishing communities',
    'Casual, Comfortable Clothing',
    'Boat',
    'Fresh Seafood, Grilled Fish',
    'Homestay',
    'Boat',
    'US$30–60',
    '06:00–18:00',
    '',
    'Bai Chay Hospital (Ha Long)',
    'Sea Water, Bottled Water',
    'Sea Water, Bottled Water'
  ),
  'vietnam-chaudoc': R(
    'Cash (VND), QR Payment',
    'Respect floating village residents',
    'Casual, Comfortable Clothing',
    'Boat',
    'Bun Ca, Fresh Seafood',
    'Homestay',
    'Boat',
    'US$30–60',
    '06:00–18:00',
    '',
    'Chau Doc Regional General Hospital',
    'River Water, Bottled Water',
    'River Water, Bottled Water'
  ),
  'vietnam-tanlap': R(
    'Cash (VND), QR Payment',
    'Keep waterways clean',
    'Casual, Comfortable Clothing',
    'Boat, Walking',
    'Elephant Ear Fish, Hotpot',
    'Eco Lodge, Homestay',
    'Car',
    'US$30–60',
    '08:00–18:00',
    '',
    'Long An General Hospital',
    'Wetland Water, Bottled Water',
    'Wetland Water, Bottled Water'
  ),
  'vietnam-catcat': R(
    'Cash (VND), QR Payment',
    'Support local handicrafts',
    'Casual, Modest Clothing',
    'Walking',
    'Thang Co, Men Men',
    'Homestay',
    'Car',
    'US$25–50',
    '07:00–18:00',
    '',
    'Sa Pa General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-lac': R(
    'Cash (VND), QR Payment',
    'Respect traditional stilt-house customs',
    'Casual, Modest Clothing',
    'Walking, Bicycle',
    'Com Lam, Grilled Chicken',
    'Homestay',
    'Car',
    'US$25–50',
    'Open 24 Hours',
    '',
    'Mai Chau District Medical Center',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-tavan': R(
    'Cash (VND), QR Payment',
    'Ask permission before entering homes',
    'Casual, Modest Clothing',
    'Hiking',
    'Thang Co, Black Chicken',
    'Homestay',
    'Car',
    'US$25–50',
    'Open 24 Hours',
    '',
    'Sa Pa General Hospital',
    'Mountain Spring, Bottled Water',
    'Mountain Spring, Bottled Water'
  ),
  'vietnam-battrang': R(
    'Cash (VND), Credit/Debit Card',
    'Support local artisans',
    'Casual, Modest Clothing',
    'Walking',
    'Pho Cuon, Bun Cha',
    'Hotel, Homestay',
    'Car',
    'US$30–60',
    '08:00–17:30',
    '',
    'Gia Lam General Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Tap Water (Not Drinkable), Bottled Water'
  ),
  'vietnam-kimbong': R(
    'Cash (VND), QR Payment',
    'Respect craftsmen at work',
    'Casual, Modest Clothing',
    'Walking',
    'Mi Quang, Cao Lau',
    'Homestay',
    'Car',
    'US$30–60',
    '08:00–17:00',
    '',
    'Hoi An Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Tap Water (Not Drinkable), Bottled Water'
  ),
  'vietnam-vanphuc': R(
    'Cash (VND), Credit/Debit Card',
    'Respect traditional weaving practices',
    'Casual, Modest Clothing',
    'Walking',
    'Pho, Bun Cha',
    'Hotel',
    'Car',
    'US$30–60',
    '08:00–17:30',
    '',
    'Ha Dong General Hospital',
    'Tap Water (Not Drinkable), Bottled Water',
    'Tap Water (Not Drinkable), Bottled Water'
  ),
};

// ---------------------------------------------------------------------------
// Merge logic
// ---------------------------------------------------------------------------
const NEW_FIELD_ORDER = [
  'paymentMethods',
  'cultureEtiquette',
  'dressCode',
  'gettingAround',
  'food',
  'stay',
  'transport',
  'costPerDay',
  'openingHours',
  'emergencyNumbers',
  'hospitals',
  'waterSource',
  'shops',
];

function applyRows(list, rows, { newBase = {}, renames = {}, renameId = {} } = {}) {
  const byId = new Map(list.map((p) => [p.id, p]));

  // rename ids first (e.g. cambodia-phoum Kandal -> cambodia-phoumkandal)
  for (const [oldId, newId] of Object.entries(renameId)) {
    const p = byId.get(oldId);
    if (p) {
      byId.delete(oldId);
      p.id = newId;
      byId.set(newId, p);
    }
  }

  // apply rows to existing places
  for (const [id, fields] of Object.entries(rows)) {
    const p = byId.get(id);
    if (!p) continue;
    for (const [k, v] of Object.entries(fields)) {
      p[k] = v;
    }
  }

  // rename combined places (location only)
  for (const [id, location] of Object.entries(renames)) {
    const p = byId.get(id);
    if (p) p.location = location;
  }

  // add brand-new places
  for (const [id, fields] of Object.entries(newBase)) {
    if (byId.has(id)) continue;
    const base = { id, ...fields };
    if (rows[id]) {
      for (const [k, v] of Object.entries(rows[id])) {
        if (v !== '') base[k] = v;
      }
    }
    byId.set(id, base);
  }

  // reorder keys: existing keys first (minus new fields), then new fields, dropping empties
  const out = [];
  for (const p of list) {
    const next = {};
    for (const k of Object.keys(p)) {
      if (NEW_FIELD_ORDER.includes(k)) continue;
      next[k] = p[k];
    }
    for (const k of NEW_FIELD_ORDER) {
      const v = p[k];
      if (v !== undefined && v !== '') next[k] = v;
    }
    out.push(next);
  }
  // new places appended at the end
  for (const id of Object.keys(newBase)) {
    const p = byId.get(id);
    if (!p || list.includes(p)) continue;
    const next = {};
    for (const k of Object.keys(p)) {
      if (NEW_FIELD_ORDER.includes(k)) continue;
      next[k] = p[k];
    }
    for (const k of NEW_FIELD_ORDER) {
      const v = p[k];
      if (v !== undefined && v !== '') next[k] = v;
    }
    out.push(next);
  }
  return out;
}

function serializeFile(exportName, places) {
  const lines = [`export const ${exportName} = [`];
  places.forEach((p, idx) => {
    lines.push('  {');
    const keys = Object.keys(p);
    keys.forEach((k, i) => {
      const comma = i < keys.length - 1 ? ',' : '';
      lines.push(`    ${k}: ${JSON.stringify(p[k])}${comma}`);
    });
    lines.push(`  }${idx < places.length - 1 ? ',' : ''}`);
  });
  lines.push('];');
  return lines.join('\n') + '\n';
}

const indonesiaMerged = applyRows(indonesiaData, IND, { newBase: IND_NEW_BASE, renames: IND_RENAME });
const cambodiaMerged = applyRows(cambodiaData, KHM, {
  renameId: { 'cambodia-phoum Kandal': 'cambodia-phoumkandal' },
});
const vietnamMerged = applyRows(vietnamData, VNM);

writeFileSync(resolve(DATA, 'indonesia.js'), serializeFile('indonesiaData', indonesiaMerged));
writeFileSync(resolve(DATA, 'cambodia.js'), serializeFile('cambodiaData', cambodiaMerged));
writeFileSync(resolve(DATA, 'vietnam.js'), serializeFile('vietnamData', vietnamMerged));

console.log(`indonesia: ${indonesiaMerged.length} places (was ${indonesiaData.length})`);
console.log(`cambodia: ${cambodiaMerged.length} places (was ${cambodiaData.length})`);
console.log(`vietnam: ${vietnamMerged.length} places (was ${vietnamData.length})`);
